name: Red Earth CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: red-earth

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Show project files
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint --if-present

      - name: Build React application
        run: npm run build